import * as vscode from "vscode";

/** A recent AI code insertion for lifecycle tracking. */
interface RecentAIInsertion {
  file: string;
  ts: number;
  linesAdded: number;
  startLine: number;
  endLine: number;
}

/** Result of checking a post-AI edit. */
export type AILifecycleEvent = "ai_code_refined" | "ai_code_undone" | "ai_code_deleted" | null;

/**
 * Tracks whether edits are human-authored or AI-assisted, AND what happens
 * to AI code after acceptance (lifecycle tracking).
 *
 * The core principle: LLM-generated code/commits should not carry the
 * same weight as human work when measuring developer focus and productivity.
 *
 * Detection signals:
 * - Edits within 5s after an AI command (inlineChat, copilot generate) → AI
 * - completion_accepted events → AI
 * - Everything else → human
 * - Commit messages generated by AI tools → AI-assisted commit
 *
 * Lifecycle tracking:
 * - AI code refined (same lines edited <30s after) → needed human touch
 * - AI code undone (<10s after) → AI was wrong
 * - AI code deleted (net removal <60s after) → rejected after trying
 */
export class AIActivityTracker implements vscode.Disposable {
  /** Timestamp of the most recent AI command per file. */
  private _lastAICommand = new Map<string, number>();
  /** Global timestamp of the most recent AI command (any file). */
  private _lastAICommandGlobal = 0;

  /** Rolling edit counts within the tracking window. */
  private _aiEdits = new Map<string, { lines: number; ts: number }[]>();
  private _humanEdits = new Map<string, { lines: number; ts: number }[]>();

  /** Whether the current pending git commit message was AI-generated. */
  private _commitAIGenerated = false;

  /** Recent AI code insertions for lifecycle tracking. */
  private _recentInsertions: RecentAIInsertion[] = [];
  private static readonly MAX_INSERTIONS = 20;

  /** How long after an AI command to classify edits as AI-assisted. */
  private static readonly AI_WINDOW_MS = 5_000;
  /** Rolling window for ratio calculations. */
  private static readonly TRACKING_WINDOW_MS = 300_000; // 5 min

  /** Lifecycle windows. */
  private static readonly UNDO_WINDOW_MS = 10_000;
  private static readonly REFINE_WINDOW_MS = 30_000;
  private static readonly DELETE_WINDOW_MS = 60_000;

  private _disposables: vscode.Disposable[] = [];

  constructor() {
    // Watch for AI-related commands.
    if (typeof (vscode.commands as any).onDidExecuteCommand === "function") {
      this._disposables.push(
        (vscode.commands as any).onDidExecuteCommand((e: { command: string }) => {
          this._onCommand(e.command);
        }),
      );
    }
  }

  /** Called when any command is executed. Detects AI-related commands. */
  private _onCommand(cmd: string): void {
    const aiCommands = [
      "inlineChat.start",
      "github.copilot.interactiveEditor.generate",
      "github.copilot.interactiveEditor.fix",
      "github.copilot.interactiveEditor.explain",
      "editor.action.inlineSuggest.commit",
      "editor.action.codeAction",
    ];
    const commitMsgCommands = [
      "github.copilot.git.generateCommitMessage",
      "git.commitMessageGenerate",
    ];

    if (aiCommands.includes(cmd)) {
      const now = Date.now();
      this._lastAICommandGlobal = now;
      const editor = vscode.window.activeTextEditor;
      if (editor) {
        this._lastAICommand.set(editor.document.uri.fsPath, now);
      }
    }
    if (commitMsgCommands.includes(cmd)) {
      this._commitAIGenerated = true;
    }
  }

  /** Record an edit. Classifies as AI or human based on recent AI commands. */
  recordEdit(filePath: string, linesChanged: number): "ai" | "human" {
    const now = Date.now();
    const lastAI = this._lastAICommand.get(filePath) ?? 0;
    const isAI =
      now - lastAI < AIActivityTracker.AI_WINDOW_MS ||
      now - this._lastAICommandGlobal < AIActivityTracker.AI_WINDOW_MS;

    const target = isAI ? this._aiEdits : this._humanEdits;
    const arr = target.get(filePath) ?? [];
    arr.push({ lines: linesChanged, ts: now });
    target.set(filePath, arr);

    return isAI ? "ai" : "human";
  }

  /** Record an accepted inline completion. Also stores for lifecycle tracking. */
  recordCompletionAccepted(
    filePath: string,
    charsAdded: number,
    startLine: number,
    endLine: number,
  ): void {
    const now = Date.now();
    const lines = Math.max(1, Math.ceil(charsAdded / 40));
    const arr = this._aiEdits.get(filePath) ?? [];
    arr.push({ lines, ts: now });
    this._aiEdits.set(filePath, arr);

    // Store for lifecycle tracking.
    this._recentInsertions.push({
      file: filePath,
      ts: now,
      linesAdded: lines,
      startLine,
      endLine,
    });
    // Cap buffer size.
    if (this._recentInsertions.length > AIActivityTracker.MAX_INSERTIONS) {
      this._recentInsertions.shift();
    }
  }

  /**
   * Check if a subsequent edit overlaps with a recent AI insertion.
   * Returns the lifecycle event type, or null if no match.
   */
  checkPostAIEdit(
    filePath: string,
    startLine: number,
    endLine: number,
    isUndo: boolean,
    linesAdded: number,
    linesRemoved: number,
  ): AILifecycleEvent {
    const now = Date.now();

    // Prune old insertions.
    this._recentInsertions = this._recentInsertions.filter(
      (ins) => now - ins.ts < AIActivityTracker.DELETE_WINDOW_MS,
    );

    // Find the most recent overlapping insertion for this file.
    for (let i = this._recentInsertions.length - 1; i >= 0; i--) {
      const ins = this._recentInsertions[i];
      if (ins.file !== filePath) continue;

      // Check line overlap (with tolerance of ±3 lines for drift).
      const overlaps =
        startLine <= ins.endLine + 3 && endLine >= ins.startLine - 3;
      if (!overlaps) continue;

      const elapsed = now - ins.ts;

      // Undo within 10s = AI was wrong.
      if (isUndo && elapsed < AIActivityTracker.UNDO_WINDOW_MS) {
        this._recentInsertions.splice(i, 1); // consume
        return "ai_code_undone";
      }

      // Net deletion within 60s = rejected after trying.
      if (
        linesRemoved > linesAdded &&
        elapsed < AIActivityTracker.DELETE_WINDOW_MS
      ) {
        this._recentInsertions.splice(i, 1);
        return "ai_code_deleted";
      }

      // Same lines modified within 30s = refinement needed.
      if (elapsed < AIActivityTracker.REFINE_WINDOW_MS) {
        this._recentInsertions.splice(i, 1);
        return "ai_code_refined";
      }

      break; // Only check the most recent match.
    }

    return null;
  }

  /** Classify an AI invocation as active (user-triggered) or passive (auto-suggestion). */
  classifyInvocation(command: string): "active" | "passive" {
    const activeCommands = [
      "inlineChat.start",
      "github.copilot.interactiveEditor.generate",
      "github.copilot.interactiveEditor.fix",
      "github.copilot.interactiveEditor.explain",
    ];
    return activeCommands.includes(command) ? "active" : "passive";
  }

  /** AI edit ratio for a specific file (0.0 = all human, 1.0 = all AI). */
  getAIRatioForFile(filePath: string): number {
    const cutoff = Date.now() - AIActivityTracker.TRACKING_WINDOW_MS;
    const ai = (this._aiEdits.get(filePath) ?? []).filter((e) => e.ts > cutoff);
    const human = (this._humanEdits.get(filePath) ?? []).filter((e) => e.ts > cutoff);
    const aiLines = ai.reduce((s, e) => s + e.lines, 0);
    const humanLines = human.reduce((s, e) => s + e.lines, 0);
    const total = aiLines + humanLines;
    return total === 0 ? 0 : aiLines / total;
  }

  /** Overall AI ratio across all files. */
  getOverallAIRatio(): number {
    const cutoff = Date.now() - AIActivityTracker.TRACKING_WINDOW_MS;
    let aiTotal = 0;
    let humanTotal = 0;
    for (const edits of this._aiEdits.values()) {
      aiTotal += edits
        .filter((e) => e.ts > cutoff)
        .reduce((s, e) => s + e.lines, 0);
    }
    for (const edits of this._humanEdits.values()) {
      humanTotal += edits
        .filter((e) => e.ts > cutoff)
        .reduce((s, e) => s + e.lines, 0);
    }
    const total = aiTotal + humanTotal;
    return total === 0 ? 0 : aiTotal / total;
  }

  /** Whether the current pending commit is AI-assisted. */
  isCommitAIAssisted(): boolean {
    return this._commitAIGenerated;
  }

  /** Reset commit AI flag (call after commit is recorded). */
  clearCommitAIFlag(): void {
    this._commitAIGenerated = false;
  }

  dispose(): void {
    this._disposables.forEach((d) => d.dispose());
  }
}
